import { TournamentFormat, Tournament, League, Club } from './types';

export const tournamentFormats: TournamentFormat[] = [
  {
    id: '1',
    name: 'Americano',
    slug: 'americano',
    description: 'Formato rotativo donde las parejas cambian cada ronda — todos juegan con todos y contra todos. Perfecto para tardes sociales y grupos de nivel mixto.',
    maxPlayers: 16,
    minPlayers: 8,
    duration: '2-3 horas',
    difficulty: 'Todos los niveles',
    type: 'Americano',
    icon: '🔄',
    rules: [
      'Los jugadores rotan de pareja después de cada ronda',
      'Cada ronda consiste en un juego hasta un número determinado de puntos (normalmente 16 o 24)',
      'Las puntuaciones individuales se acumulan durante todo el torneo',
      'Gana el jugador con más puntos al final',
      'Sin parejas fijas — todos juegan con y contra todos',
    ],
    pros: [
      'Ideal para relacionarse y conocer nuevos jugadores',
      'Funciona muy bien con niveles mixtos',
      'Todos permanecen activos durante todo el torneo',
      'Sistema de puntuación simple y transparente',
      'Perfecto para eventos sociales de club',
    ],
    idealFor: 'Eventos sociales, noches de club e introducción de nuevos jugadores al deporte',
  },
  {
    id: '2',
    name: 'Mexicano',
    slug: 'mexicano',
    description: 'Formato dinámico donde, tras la primera ronda, las parejas se forman según la puntuación acumulada — los mejores juegan juntos y entre sí. Crea un equilibrio competitivo natural de forma automática.',
    maxPlayers: 16,
    minPlayers: 8,
    duration: '2-4 horas',
    difficulty: 'Todos los niveles',
    type: 'Mexicano',
    icon: '⚡',
    rules: [
      'Primera ronda: las parejas son aleatorias',
      'Rondas siguientes: los jugadores clasificados 1.º y 2.º juegan juntos, 3.º y 4.º juntos, y así sucesivamente',
      'Los equipos también enfrentan rivales de rango similar',
      'Los puntos individuales se acumulan en todas las rondas',
      'El reequilibrio dinámico garantiza partidos competitivos en todo momento',
    ],
    pros: [
      'El auto-balanceo crea partidos siempre competitivos',
      'Los mejores enfrentan a los mejores; los principiantes, a los principiantes',
      'Emocionante para jugadores de todos los niveles',
      'El ranking surge de forma natural durante el torneo',
      'Sensación de torneo de alta intensidad de principio a fin',
    ],
    idealFor: 'Grupos de nivel mixto que buscan partidos competitivos y equilibrados',
  },
  {
    id: '3',
    name: 'Round Robin',
    slug: 'round-robin',
    description: 'Cada jugador o equipo se enfrenta a todos los demás al menos una vez. El formato más completo para determinar un ranking real — todos se ganan su lugar por mérito.',
    maxPlayers: 16,
    minPlayers: 4,
    duration: '4-6 horas',
    difficulty: 'Todos los niveles',
    type: 'Round Robin',
    icon: '📋',
    rules: [
      'Cada equipo juega contra todos los demás exactamente una vez',
      'Puntos: 3 por victoria, 1 por empate, 0 por derrota',
      'La clasificación final se determina por puntos totales',
      'Desempate: resultado directo entre los empatados, luego diferencia de juegos',
      'Sin eliminación — todos los equipos juegan el calendario completo',
    ],
    pros: [
      'El formato más justo — todos juegan contra todos',
      'Sin mala suerte por el sorteo del cuadro',
      'Garantiza el máximo número de partidos para todos los participantes',
      'Clasificación final clara del primero al último',
      'Ideal para determinar al campeón real del club o liga',
    ],
    idealFor: 'Campeonatos de club, finales de ligas pequeñas y eventos que requieren una clasificación definitiva',
  },
  {
    id: '4',
    name: 'Team League',
    slug: 'team-league',
    description: 'Equipos de jugadores compiten en torneos de varias semanas con partidos de local y visitante. La experiencia completa de liga: tabla de posiciones, ascensos y descensos.',
    maxPlayers: 48,
    minPlayers: 16,
    duration: 'Multi-jornada',
    difficulty: 'Todos los niveles',
    type: 'Liga',
    icon: '📊',
    rules: [
      'Equipos de 2 a 4 jugadores cada uno',
      'Partidos de local y visitante programados durante varias semanas',
      'Los puntos se acumulan en la tabla de posiciones',
      'Los equipos líderes ascienden; los últimos descienden',
      'Play-offs por el campeonato al final de la temporada',
    ],
    pros: [
      'Experiencia de temporada completa',
      'Genera identidad de equipo y rivalidades duraderas',
      'Compromiso a largo plazo para los jugadores',
      'Drama natural de ascenso y descenso',
      'Perfecto para competencias club contra club',
    ],
    idealFor: 'Ligas de clubes, ligas de ciudad y competencias nacionales a lo largo de una temporada',
  },
  {
    id: '5',
    name: 'Knockout',
    slug: 'knockout',
    description: 'Cuadro de eliminación directa clásico. Ganás y avanzás, perdés y te vas. Partidos de alto riesgo desde la primera ronda con la tensión de la muerte súbita.',
    maxPlayers: 16,
    minPlayers: 4,
    duration: '4-8 horas',
    difficulty: 'Intermedio',
    type: 'Eliminación',
    icon: '🏆',
    rules: [
      'El sorteo del cuadro determina los enfrentamientos iniciales',
      'Mejor de 3 sets por partido (o set único con tie-break en formato corto)',
      'El perdedor queda eliminado de inmediato',
      'El ganador avanza a la siguiente ronda',
      'La final determina al campeón y subcampeón',
    ],
    pros: [
      'Alta tensión y emoción en cada partido',
      'Surge un ganador claro e indiscutible',
      'Formato ampliamente conocido por todos',
      'Ideal para eventos de prestigio y alta competencia',
      'Construye hacia una final memorable',
    ],
    idealFor: 'Torneos competitivos, campeonatos y eventos de club de alto nivel',
  },
  {
    id: '6',
    name: 'World Cup',
    slug: 'world-cup',
    description: 'El formato más emocionante del pádel: grupos de 4 equipos donde los 2 mejores clasifican a un cuadro de eliminación directa estilo FIFA. Alta competencia desde la primera ronda.',
    maxPlayers: 64,
    minPlayers: 16,
    duration: '2–3 jornadas',
    difficulty: 'Intermediate',
    type: 'Knockout',
    icon: '🏅',
    rules: [
      'Se forman grupos de 4 equipos',
      'Todos los equipos del grupo juegan entre sí (round robin interno)',
      'Los 2 mejores de cada grupo clasifican al cuadro eliminatorio',
      'El cuadro sigue con octavos, cuartos, semis y final',
      'Posibilidad de partido por el 3er puesto',
    ],
    pros: [
      'Garantiza al menos 3 partidos por equipo',
      'El formato más reconocible del mundo del deporte',
      'Combina round robin con la tensión del cuadro eliminatorio',
      'Ideal para grandes eventos y torneos de club',
      'Disponible en 4 u 8 grupos según el número de equipos',
    ],
    idealFor: 'Torneos grandes, finales de temporada y eventos especiales de club',
  },
];

export const ongoingTournaments: Tournament[] = [
  {
    id: 'da05effb-cada-4351-8946-b27ecf0c4961',
    name: 'Madrid Spring Americano',
    format: 'Americano',
    formatSlug: 'americano',
    status: 'ongoing',
    startDate: '2026-04-28',
    endDate: '2026-04-28',
    club: 'Padel Madrid Central',
    city: 'Madrid',
    country: 'Spain',
    players: 12,
    maxPlayers: 12,
    category: 'Open',
    level: 'All levels',
  },
  {
    id: 'b12c3456-def0-7890-abcd-ef1234567890',
    name: 'Barcelona Mexicano Cup',
    format: 'Mexicano',
    formatSlug: 'mexicano',
    status: 'ongoing',
    startDate: '2026-04-28',
    endDate: '2026-04-28',
    club: 'Club Padel Barcelona',
    city: 'Barcelona',
    country: 'Spain',
    players: 16,
    maxPlayers: 16,
    category: 'Competitive',
    level: 'Intermediate',
  },
  {
    id: 'c23d4567-ef01-8901-bcde-f01234567891',
    name: 'London Padel League Round 5',
    format: 'Round Robin',
    formatSlug: 'round-robin',
    status: 'ongoing',
    startDate: '2026-04-25',
    endDate: '2026-05-10',
    club: 'Padel London Arena',
    city: 'London',
    country: 'UK',
    players: 8,
    maxPlayers: 8,
    category: 'League',
    level: 'Advanced',
  },
  {
    id: 'd34e5678-f012-9012-cdef-012345678902',
    name: 'Paris Open Knockout',
    format: 'Knockout',
    formatSlug: 'knockout',
    status: 'upcoming',
    startDate: '2026-05-03',
    endDate: '2026-05-03',
    club: 'Paris Padel Club',
    city: 'Paris',
    country: 'France',
    players: 8,
    maxPlayers: 16,
    category: 'Open',
    prize: '€500',
    level: 'Intermediate',
  },
  {
    id: 'e45f6789-0123-0123-def0-123456789013',
    name: 'Dubai International Swiss',
    format: 'Swiss System',
    formatSlug: 'swiss',
    status: 'upcoming',
    startDate: '2026-05-10',
    endDate: '2026-05-10',
    club: 'Dubai Padel Academy',
    city: 'Dubai',
    country: 'UAE',
    players: 0,
    maxPlayers: 32,
    category: 'International',
    prize: '$2,000',
    level: 'Advanced',
  },
  {
    id: 'f56g7890-1234-1234-ef01-234567890124',
    name: 'Amsterdam City Americano',
    format: 'Americano',
    formatSlug: 'americano',
    status: 'completed',
    startDate: '2026-04-20',
    endDate: '2026-04-20',
    club: 'Amsterdam Padel Center',
    city: 'Amsterdam',
    country: 'Netherlands',
    players: 12,
    maxPlayers: 12,
    category: 'Social',
    level: 'All levels',
  },
];

export const leagues: League[] = [
  {
    id: '1',
    name: 'Liga Nacional de Pádel España',
    organizer: 'Real Federación Española de Pádel',
    country: 'Spain',
    city: 'Madrid',
    season: '2026',
    status: 'active',
    teams: 12,
    players: 48,
    startDate: '2026-02-01',
    endDate: '2026-06-30',
    category: 'Professional',
    level: 'Elite',
    description: 'The premier padel league in Spain featuring the best club teams competing across the nation.',
  },
  {
    id: '2',
    name: 'Premier Padel London',
    organizer: 'London Padel Association',
    country: 'UK',
    city: 'London',
    season: '2026',
    status: 'active',
    teams: 8,
    players: 32,
    startDate: '2026-03-01',
    endDate: '2026-07-31',
    category: 'Amateur',
    level: 'Intermediate',
    description: 'London\'s leading amateur padel league, open to all clubs in the greater London area.',
  },
  {
    id: '3',
    name: 'Ligue Nationale Padel France',
    organizer: 'Fédération Française de Padel',
    country: 'France',
    city: 'Paris',
    season: '2026',
    status: 'active',
    teams: 10,
    players: 40,
    startDate: '2026-01-15',
    endDate: '2026-06-15',
    category: 'Mixed',
    level: 'All levels',
    description: 'The national league of France open to clubs of all levels across the country.',
  },
  {
    id: '4',
    name: 'Dubai Padel Pro League',
    organizer: 'UAE Padel Federation',
    country: 'UAE',
    city: 'Dubai',
    season: '2026',
    status: 'upcoming',
    teams: 6,
    players: 24,
    startDate: '2026-06-01',
    endDate: '2026-09-30',
    category: 'Professional',
    level: 'Elite',
    description: 'Elite padel competition in the UAE bringing together the region\'s top players.',
  },
  {
    id: '5',
    name: 'Bundesliga Padel',
    organizer: 'Deutscher Padel Verband',
    country: 'Germany',
    city: 'Berlin',
    season: '2026',
    status: 'active',
    teams: 8,
    players: 32,
    startDate: '2026-02-15',
    endDate: '2026-07-15',
    category: 'Amateur',
    level: 'Intermediate',
    description: 'Germany\'s national padel league bringing together clubs from across the country.',
  },
  {
    id: '6',
    name: 'Italian Padel Series',
    organizer: 'Federazione Italiana Tennis e Padel',
    country: 'Italy',
    city: 'Rome',
    season: '2026',
    status: 'upcoming',
    teams: 10,
    players: 40,
    startDate: '2026-05-01',
    endDate: '2026-09-30',
    category: 'Mixed',
    level: 'All levels',
    description: 'Italy\'s leading padel series open to clubs and individuals across the peninsula.',
  },
];

export const clubs: Club[] = [
  {
    id: '1',
    name: 'Padel Madrid Central',
    country: 'Spain',
    city: 'Madrid',
    address: 'Calle de Alcalá 150, Madrid',
    courts: 8,
    members: 450,
    rating: 4.8,
    amenities: ['Changing rooms', 'Pro shop', 'Restaurant', 'Coaching', 'Parking'],
    phone: '+34 91 123 4567',
    email: 'info@padelmadridcentral.com',
  },
  {
    id: '2',
    name: 'Club Padel Barcelona',
    country: 'Spain',
    city: 'Barcelona',
    address: 'Av. Diagonal 200, Barcelona',
    courts: 6,
    members: 380,
    rating: 4.7,
    amenities: ['Changing rooms', 'Bar', 'Coaching', 'Parking', 'Kids area'],
    phone: '+34 93 456 7890',
    email: 'contacto@cpbarcelona.es',
  },
  {
    id: '3',
    name: 'Padel London Arena',
    country: 'UK',
    city: 'London',
    address: '45 Sports Way, Battersea, London',
    courts: 5,
    members: 320,
    rating: 4.6,
    amenities: ['Changing rooms', 'Cafe', 'Coaching', 'Equipment rental'],
    phone: '+44 20 7123 4567',
    email: 'hello@padellondon.co.uk',
  },
  {
    id: '4',
    name: 'Paris Padel Club',
    country: 'France',
    city: 'Paris',
    address: '12 Rue du Sport, Paris 16e',
    courts: 4,
    members: 280,
    rating: 4.5,
    amenities: ['Changing rooms', 'Brasserie', 'Pro shop', 'Coaching'],
    phone: '+33 1 23 45 67 89',
    email: 'contact@parispadel.fr',
  },
  {
    id: '5',
    name: 'Amsterdam Padel Center',
    country: 'Netherlands',
    city: 'Amsterdam',
    address: 'Sportpark West 88, Amsterdam',
    courts: 6,
    members: 290,
    rating: 4.7,
    amenities: ['Changing rooms', 'Cafe', 'Coaching', 'Parking', 'Shop'],
    phone: '+31 20 123 4567',
    email: 'info@amsterdampadel.nl',
  },
  {
    id: '6',
    name: 'Dubai Padel Academy',
    country: 'UAE',
    city: 'Dubai',
    address: 'Sports City Road, Dubai',
    courts: 10,
    members: 600,
    rating: 4.9,
    amenities: ['Changing rooms', 'Restaurant', 'Pro shop', 'Coaching', 'Parking', 'Pool'],
    phone: '+971 4 123 4567',
    email: 'play@dubaipadel.ae',
  },
  {
    id: '7',
    name: 'Berlin Padel Halle',
    country: 'Germany',
    city: 'Berlin',
    address: 'Sportpark Mitte 55, Berlin',
    courts: 5,
    members: 240,
    rating: 4.4,
    amenities: ['Changing rooms', 'Cafe', 'Coaching', 'Parking'],
    phone: '+49 30 1234 5678',
    email: 'info@berlinpadel.de',
  },
  {
    id: '8',
    name: 'Rome Padel Sports',
    country: 'Italy',
    city: 'Rome',
    address: 'Via dello Sport 23, Roma',
    courts: 4,
    members: 200,
    rating: 4.3,
    amenities: ['Changing rooms', 'Bar', 'Coaching'],
    phone: '+39 06 1234 5678',
    email: 'info@romepadel.it',
  },
];

export const countries = ['All Countries', 'Spain', 'UK', 'France', 'Netherlands', 'UAE', 'Germany', 'Italy'];

export const cities: Record<string, string[]> = {
  'All Countries': ['All Cities'],
  'Spain': ['All Cities', 'Madrid', 'Barcelona', 'Valencia', 'Seville'],
  'UK': ['All Cities', 'London', 'Manchester', 'Birmingham'],
  'France': ['All Cities', 'Paris', 'Lyon', 'Marseille'],
  'Netherlands': ['All Cities', 'Amsterdam', 'Rotterdam', 'The Hague'],
  'UAE': ['All Cities', 'Dubai', 'Abu Dhabi'],
  'Germany': ['All Cities', 'Berlin', 'Munich', 'Hamburg'],
  'Italy': ['All Cities', 'Rome', 'Milan', 'Naples'],
};
