import { TournamentFormat, Tournament, League, Club } from './types';

export const tournamentFormats: TournamentFormat[] = [
  {
    id: '1',
    name: 'Americano',
    slug: 'americano',
    description: 'A fun rotating-partner format where players change partners every round, ensuring everyone plays with and against each other. Perfect for social events and mixed-level groups.',
    maxPlayers: 16,
    minPlayers: 8,
    duration: '2-3 hours',
    difficulty: 'All levels',
    type: 'Americano',
    icon: '🔄',
    rules: [
      'Players rotate partners after each round',
      'Each round consists of one game to a set number of points (usually 16 or 24)',
      'Individual scores are accumulated throughout the tournament',
      'The player with the most points at the end wins',
      'No fixed partners — everyone plays with and against everyone',
    ],
    pros: [
      'Great for social mixing and meeting new players',
      'Works well with mixed skill levels',
      'Everyone stays active throughout',
      'Simple scoring system',
      'Ideal for club social events',
    ],
    idealFor: 'Social events, club nights, and introducing new players to the sport',
  },
  {
    id: '2',
    name: 'Mexicano',
    slug: 'mexicano',
    description: 'A dynamic format where after the first round, players are paired based on their scores — top scorers play together and against each other. Creates natural competitive balance.',
    maxPlayers: 16,
    minPlayers: 8,
    duration: '2-4 hours',
    difficulty: 'All levels',
    type: 'Mexicano',
    icon: '⚡',
    rules: [
      'First round: players are randomly paired',
      'Subsequent rounds: players ranked 1st and 2nd play together, 3rd and 4th together, etc.',
      'Teams also face opponents of similar ranking',
      'Individual points accumulate across all rounds',
      'Dynamic rebalancing ensures competitive matches throughout',
    ],
    pros: [
      'Self-balancing format creates competitive matches',
      'Strong players face strong opponents, beginners face beginners',
      'Exciting for players of all levels',
      'Natural ranking system emerges',
      'Great tournament feel from start to finish',
    ],
    idealFor: 'Mixed-skill groups wanting competitive yet fair matches',
  },
  {
    id: '3',
    name: 'Round Robin',
    slug: 'round-robin',
    description: 'Every team plays against every other team. The team with the most points/wins at the end takes the title. A thorough format that finds the true best team.',
    maxPlayers: 12,
    minPlayers: 4,
    duration: '3-6 hours',
    difficulty: 'All levels',
    type: 'Round Robin',
    icon: '🔁',
    rules: [
      'Fixed partnerships throughout the tournament',
      'Each pair plays every other pair at least once',
      'Points awarded: 3 for a win, 1 for a draw, 0 for a loss',
      'Set difference used as tiebreaker',
      'Top team after all matches wins',
    ],
    pros: [
      'Most fair format — everyone plays everyone',
      'Guarantees minimum number of matches',
      'Great for determining true rankings',
      'No early elimination',
      'Ideal for league-style competitions',
    ],
    idealFor: 'League rounds, club championships, and competitive club events',
  },
  {
    id: '4',
    name: 'Knockout',
    slug: 'knockout',
    description: 'Classic single-elimination bracket. Win and advance, lose and go home. High-stakes matches from round one with the drama of sudden-death competition.',
    maxPlayers: 16,
    minPlayers: 4,
    duration: '4-8 hours',
    difficulty: 'Intermediate',
    type: 'Knockout',
    icon: '🏆',
    rules: [
      'Bracket draw determines initial matchups',
      'Best of 3 sets per match (or single set with tiebreak for shorter format)',
      'Loser is eliminated immediately',
      'Winner advances to next round',
      'Finals determine champion and runner-up',
    ],
    pros: [
      'High drama and excitement',
      'Clear winner emerges',
      'Well-understood format',
      'Great for prestigious events',
      'Builds to a memorable final',
    ],
    idealFor: 'Competitive tournaments, championships, and prestigious club events',
  },
  {
    id: '5',
    name: 'Swiss System',
    slug: 'swiss',
    description: 'Players with similar win/loss records are matched in each round. No elimination — everyone plays all rounds, but strong players face increasingly tough opposition.',
    maxPlayers: 32,
    minPlayers: 8,
    duration: '4-6 hours',
    difficulty: 'Advanced',
    type: 'Swiss',
    icon: '🎯',
    rules: [
      'No elimination — all players complete all rounds',
      'Round 1: Random pairings',
      'Subsequent rounds: Players with same record face each other',
      'Points: 1 for win, 0.5 for draw, 0 for loss',
      'Final ranking by total points (tiebreakers apply)',
    ],
    pros: [
      'No early elimination keeps everyone engaged',
      'Competitive matches at all levels',
      'Handles large player pools efficiently',
      'Fair ranking emerges over time',
      'Popular in chess and racket sports',
    ],
    idealFor: 'Large tournaments and federations wanting fair ranking without elimination',
  },
  {
    id: '6',
    name: 'Team League',
    slug: 'team-league',
    description: 'Teams of players compete in multi-week competitions with home and away matches. The full league experience with standings, promotions, and relegations.',
    maxPlayers: 48,
    minPlayers: 16,
    duration: 'Multi-week',
    difficulty: 'All levels',
    type: 'Round Robin',
    icon: '📊',
    rules: [
      'Teams of 2-4 players each',
      'Home and away matches scheduled over multiple weeks',
      'Points accumulate in a league table',
      'Top teams promoted, bottom teams relegated',
      'Play-offs for championship if applicable',
    ],
    pros: [
      'Full season experience',
      'Builds team identity and rivalry',
      'Long-term engagement for players',
      'Natural promotion/relegation drama',
      'Perfect for club-vs-club competitions',
    ],
    idealFor: 'Club leagues, city leagues, and national competitions spanning a season',
  },
];

export const ongoingTournaments: Tournament[] = [
  {
    id: 'da05effb-cada-4351-8946-b27ecf0c4961',
    name: 'Madrid Spring Americano',
    format: 'Americano',
    formatSlug: 'americano',
    status: 'ongoing',
    startDate: '2026-04-28',
    endDate: '2026-04-28',
    club: 'Padel Madrid Central',
    city: 'Madrid',
    country: 'Spain',
    players: 12,
    maxPlayers: 12,
    category: 'Open',
    level: 'All levels',
  },
  {
    id: 'b12c3456-def0-7890-abcd-ef1234567890',
    name: 'Barcelona Mexicano Cup',
    format: 'Mexicano',
    formatSlug: 'mexicano',
    status: 'ongoing',
    startDate: '2026-04-28',
    endDate: '2026-04-28',
    club: 'Club Padel Barcelona',
    city: 'Barcelona',
    country: 'Spain',
    players: 16,
    maxPlayers: 16,
    category: 'Competitive',
    level: 'Intermediate',
  },
  {
    id: 'c23d4567-ef01-8901-bcde-f01234567891',
    name: 'London Padel League Round 5',
    format: 'Round Robin',
    formatSlug: 'round-robin',
    status: 'ongoing',
    startDate: '2026-04-25',
    endDate: '2026-05-10',
    club: 'Padel London Arena',
    city: 'London',
    country: 'UK',
    players: 8,
    maxPlayers: 8,
    category: 'League',
    level: 'Advanced',
  },
  {
    id: 'd34e5678-f012-9012-cdef-012345678902',
    name: 'Paris Open Knockout',
    format: 'Knockout',
    formatSlug: 'knockout',
    status: 'upcoming',
    startDate: '2026-05-03',
    endDate: '2026-05-03',
    club: 'Paris Padel Club',
    city: 'Paris',
    country: 'France',
    players: 8,
    maxPlayers: 16,
    category: 'Open',
    prize: '€500',
    level: 'Intermediate',
  },
  {
    id: 'e45f6789-0123-0123-def0-123456789013',
    name: 'Dubai International Swiss',
    format: 'Swiss System',
    formatSlug: 'swiss',
    status: 'upcoming',
    startDate: '2026-05-10',
    endDate: '2026-05-10',
    club: 'Dubai Padel Academy',
    city: 'Dubai',
    country: 'UAE',
    players: 0,
    maxPlayers: 32,
    category: 'International',
    prize: '$2,000',
    level: 'Advanced',
  },
  {
    id: 'f56g7890-1234-1234-ef01-234567890124',
    name: 'Amsterdam City Americano',
    format: 'Americano',
    formatSlug: 'americano',
    status: 'completed',
    startDate: '2026-04-20',
    endDate: '2026-04-20',
    club: 'Amsterdam Padel Center',
    city: 'Amsterdam',
    country: 'Netherlands',
    players: 12,
    maxPlayers: 12,
    category: 'Social',
    level: 'All levels',
  },
];

export const leagues: League[] = [
  {
    id: '1',
    name: 'Liga Nacional de Pádel España',
    organizer: 'Real Federación Española de Pádel',
    country: 'Spain',
    city: 'Madrid',
    season: '2026',
    status: 'active',
    teams: 12,
    players: 48,
    startDate: '2026-02-01',
    endDate: '2026-06-30',
    category: 'Professional',
    level: 'Elite',
    description: 'The premier padel league in Spain featuring the best club teams competing across the nation.',
  },
  {
    id: '2',
    name: 'Premier Padel London',
    organizer: 'London Padel Association',
    country: 'UK',
    city: 'London',
    season: '2026',
    status: 'active',
    teams: 8,
    players: 32,
    startDate: '2026-03-01',
    endDate: '2026-07-31',
    category: 'Amateur',
    level: 'Intermediate',
    description: 'London\'s leading amateur padel league, open to all clubs in the greater London area.',
  },
  {
    id: '3',
    name: 'Ligue Nationale Padel France',
    organizer: 'Fédération Française de Padel',
    country: 'France',
    city: 'Paris',
    season: '2026',
    status: 'active',
    teams: 10,
    players: 40,
    startDate: '2026-01-15',
    endDate: '2026-06-15',
    category: 'Mixed',
    level: 'All levels',
    description: 'The national league of France open to clubs of all levels across the country.',
  },
  {
    id: '4',
    name: 'Dubai Padel Pro League',
    organizer: 'UAE Padel Federation',
    country: 'UAE',
    city: 'Dubai',
    season: '2026',
    status: 'upcoming',
    teams: 6,
    players: 24,
    startDate: '2026-06-01',
    endDate: '2026-09-30',
    category: 'Professional',
    level: 'Elite',
    description: 'Elite padel competition in the UAE bringing together the region\'s top players.',
  },
  {
    id: '5',
    name: 'Bundesliga Padel',
    organizer: 'Deutscher Padel Verband',
    country: 'Germany',
    city: 'Berlin',
    season: '2026',
    status: 'active',
    teams: 8,
    players: 32,
    startDate: '2026-02-15',
    endDate: '2026-07-15',
    category: 'Amateur',
    level: 'Intermediate',
    description: 'Germany\'s national padel league bringing together clubs from across the country.',
  },
  {
    id: '6',
    name: 'Italian Padel Series',
    organizer: 'Federazione Italiana Tennis e Padel',
    country: 'Italy',
    city: 'Rome',
    season: '2026',
    status: 'upcoming',
    teams: 10,
    players: 40,
    startDate: '2026-05-01',
    endDate: '2026-09-30',
    category: 'Mixed',
    level: 'All levels',
    description: 'Italy\'s leading padel series open to clubs and individuals across the peninsula.',
  },
];

export const clubs: Club[] = [
  {
    id: '1',
    name: 'Padel Madrid Central',
    country: 'Spain',
    city: 'Madrid',
    address: 'Calle de Alcalá 150, Madrid',
    courts: 8,
    members: 450,
    rating: 4.8,
    amenities: ['Changing rooms', 'Pro shop', 'Restaurant', 'Coaching', 'Parking'],
    phone: '+34 91 123 4567',
    email: 'info@padelmadridcentral.com',
  },
  {
    id: '2',
    name: 'Club Padel Barcelona',
    country: 'Spain',
    city: 'Barcelona',
    address: 'Av. Diagonal 200, Barcelona',
    courts: 6,
    members: 380,
    rating: 4.7,
    amenities: ['Changing rooms', 'Bar', 'Coaching', 'Parking', 'Kids area'],
    phone: '+34 93 456 7890',
    email: 'contacto@cpbarcelona.es',
  },
  {
    id: '3',
    name: 'Padel London Arena',
    country: 'UK',
    city: 'London',
    address: '45 Sports Way, Battersea, London',
    courts: 5,
    members: 320,
    rating: 4.6,
    amenities: ['Changing rooms', 'Cafe', 'Coaching', 'Equipment rental'],
    phone: '+44 20 7123 4567',
    email: 'hello@padellondon.co.uk',
  },
  {
    id: '4',
    name: 'Paris Padel Club',
    country: 'France',
    city: 'Paris',
    address: '12 Rue du Sport, Paris 16e',
    courts: 4,
    members: 280,
    rating: 4.5,
    amenities: ['Changing rooms', 'Brasserie', 'Pro shop', 'Coaching'],
    phone: '+33 1 23 45 67 89',
    email: 'contact@parispadel.fr',
  },
  {
    id: '5',
    name: 'Amsterdam Padel Center',
    country: 'Netherlands',
    city: 'Amsterdam',
    address: 'Sportpark West 88, Amsterdam',
    courts: 6,
    members: 290,
    rating: 4.7,
    amenities: ['Changing rooms', 'Cafe', 'Coaching', 'Parking', 'Shop'],
    phone: '+31 20 123 4567',
    email: 'info@amsterdampadel.nl',
  },
  {
    id: '6',
    name: 'Dubai Padel Academy',
    country: 'UAE',
    city: 'Dubai',
    address: 'Sports City Road, Dubai',
    courts: 10,
    members: 600,
    rating: 4.9,
    amenities: ['Changing rooms', 'Restaurant', 'Pro shop', 'Coaching', 'Parking', 'Pool'],
    phone: '+971 4 123 4567',
    email: 'play@dubaipadel.ae',
  },
  {
    id: '7',
    name: 'Berlin Padel Halle',
    country: 'Germany',
    city: 'Berlin',
    address: 'Sportpark Mitte 55, Berlin',
    courts: 5,
    members: 240,
    rating: 4.4,
    amenities: ['Changing rooms', 'Cafe', 'Coaching', 'Parking'],
    phone: '+49 30 1234 5678',
    email: 'info@berlinpadel.de',
  },
  {
    id: '8',
    name: 'Rome Padel Sports',
    country: 'Italy',
    city: 'Rome',
    address: 'Via dello Sport 23, Roma',
    courts: 4,
    members: 200,
    rating: 4.3,
    amenities: ['Changing rooms', 'Bar', 'Coaching'],
    phone: '+39 06 1234 5678',
    email: 'info@romepadel.it',
  },
];

export const countries = ['All Countries', 'Spain', 'UK', 'France', 'Netherlands', 'UAE', 'Germany', 'Italy'];

export const cities: Record<string, string[]> = {
  'All Countries': ['All Cities'],
  'Spain': ['All Cities', 'Madrid', 'Barcelona', 'Valencia', 'Seville'],
  'UK': ['All Cities', 'London', 'Manchester', 'Birmingham'],
  'France': ['All Cities', 'Paris', 'Lyon', 'Marseille'],
  'Netherlands': ['All Cities', 'Amsterdam', 'Rotterdam', 'The Hague'],
  'UAE': ['All Cities', 'Dubai', 'Abu Dhabi'],
  'Germany': ['All Cities', 'Berlin', 'Munich', 'Hamburg'],
  'Italy': ['All Cities', 'Rome', 'Milan', 'Naples'],
};
